-- Online Kahvem monetization authority
-- Rewarded ads and Google Play purchases are credited only after server verification.

create table if not exists public.rewarded_ad_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  device_hash text not null,
  status text not null default 'pending'
    check (status in ('pending', 'credited', 'expired', 'rejected')),
  reward_chips bigint not null default 500 check (reward_chips > 0),
  transaction_id text unique,
  ad_unit text,
  reward_item text,
  reward_amount numeric,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '20 minutes'),
  rewarded_at timestamptz
);

create index if not exists rewarded_ad_sessions_user_created_idx
  on public.rewarded_ad_sessions(user_id, created_at desc);

alter table public.rewarded_ad_sessions enable row level security;
revoke all on public.rewarded_ad_sessions from anon, authenticated;

create table if not exists public.play_purchase_receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  purchase_token text not null unique,
  order_id text,
  package_name text not null,
  product_type text not null check (product_type in ('consumable', 'subscription')),
  state text not null default 'pending'
    check (state in ('pending', 'verified', 'rejected', 'refunded')),
  raw_receipt jsonb not null default '{}'::jsonb,
  store_response jsonb,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create index if not exists play_purchase_receipts_user_created_idx
  on public.play_purchase_receipts(user_id, created_at desc);

alter table public.play_purchase_receipts enable row level security;
revoke all on public.play_purchase_receipts from anon, authenticated;

create or replace function public.begin_rewarded_ad(p_device_hash text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_vip_until timestamptz;
  v_used integer;
  v_last timestamptz;
  v_session uuid;
  v_wait integer;
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'error', 'auth_required'); end if;
  if coalesce(length(trim(p_device_hash)), 0) < 16 then
    return jsonb_build_object('ok', false, 'error', 'device_required');
  end if;

  select coalesce(role, 'normal'), vip_until
    into v_role, v_vip_until
    from public.profiles where id::text = v_uid::text;
  if v_role <> 'admin' and (v_role = 'vip' or (v_vip_until is not null and v_vip_until > now())) then
    return jsonb_build_object('ok', false, 'error', 'vip_no_ads');
  end if;

  update public.rewarded_ad_sessions
     set status = 'expired'
   where user_id = v_uid and status = 'pending' and expires_at <= now();

  select count(*)::integer, max(created_at)
    into v_used, v_last
    from public.rewarded_ad_sessions
   where user_id = v_uid
     and created_at >= date_trunc('day', now())
     and status in ('pending', 'credited');

  if v_used >= 5 then
    return jsonb_build_object('ok', false, 'error', 'daily_limit', 'used', v_used,
      'remaining', 0, 'cooldown_seconds', 0);
  end if;

  v_wait := greatest(0, ceil(extract(epoch from ((v_last + interval '15 minutes') - now())))::integer);
  if v_last is not null and v_wait > 0 then
    return jsonb_build_object('ok', false, 'error', 'cooldown', 'used', v_used,
      'remaining', greatest(0, 5 - v_used), 'cooldown_seconds', v_wait);
  end if;

  insert into public.rewarded_ad_sessions(user_id, device_hash)
  values (v_uid, trim(p_device_hash)) returning id into v_session;

  return jsonb_build_object('ok', true, 'session_id', v_session::text,
    'custom_data', v_session::text, 'used', v_used,
    'remaining', greatest(0, 4 - v_used), 'cooldown_seconds', 0);
end;
$$;

create or replace function public.get_rewarded_ad_state(p_session_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_status text;
  v_reward bigint := 0;
  v_used integer := 0;
  v_last timestamptz;
  v_wait integer := 0;
  v_chips bigint := 0;
begin
  if v_uid is null then return jsonb_build_object('ok', false, 'error', 'auth_required'); end if;
  if p_session_id is not null then
    select status, reward_chips into v_status, v_reward
      from public.rewarded_ad_sessions where id = p_session_id and user_id = v_uid;
  end if;
  select count(*)::integer, max(created_at)
    into v_used, v_last
    from public.rewarded_ad_sessions
   where user_id = v_uid and created_at >= date_trunc('day', now())
     and status in ('pending', 'credited');
  if v_last is not null then
    v_wait := greatest(0, ceil(extract(epoch from ((v_last + interval '15 minutes') - now())))::integer);
  end if;
  select coalesce(chips, 0) into v_chips
    from public.profiles where id::text = v_uid::text;
  return jsonb_build_object('ok', true, 'status', coalesce(v_status, ''),
    'credited', v_status = 'credited', 'reward_chips', v_reward, 'chips', v_chips,
    'used', v_used, 'remaining', greatest(0, 5 - v_used), 'cooldown_seconds', v_wait);
end;
$$;

-- Service-role only. The public HTTP server calls this after cryptographic SSV verification.
create or replace function public.finalize_rewarded_ad(
  p_session_id uuid,
  p_transaction_id text,
  p_ad_unit text,
  p_reward_item text,
  p_reward_amount numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.rewarded_ad_sessions%rowtype;
  v_chips bigint;
begin
  if current_user not in ('service_role', 'postgres') then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  if coalesce(trim(p_transaction_id), '') = '' then
    return jsonb_build_object('ok', false, 'error', 'transaction_required');
  end if;

  select * into v_row from public.rewarded_ad_sessions
   where id = p_session_id for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'session_not_found'); end if;
  if v_row.status = 'credited' then
    return jsonb_build_object('ok', true, 'duplicate', true, 'chips',
      (select chips from public.profiles where id::text = v_row.user_id::text));
  end if;
  if v_row.status <> 'pending' or v_row.expires_at <= now() then
    update public.rewarded_ad_sessions set status = 'expired' where id = p_session_id;
    return jsonb_build_object('ok', false, 'error', 'session_expired');
  end if;
  if exists(select 1 from public.rewarded_ad_sessions where transaction_id = p_transaction_id) then
    return jsonb_build_object('ok', false, 'error', 'transaction_reused');
  end if;

  update public.profiles set chips = chips + v_row.reward_chips
    where id::text = v_row.user_id::text
    returning chips into v_chips;
  update public.rewarded_ad_sessions
     set status = 'credited', transaction_id = p_transaction_id, ad_unit = p_ad_unit,
         reward_item = p_reward_item, reward_amount = p_reward_amount, rewarded_at = now()
   where id = p_session_id;
  return jsonb_build_object('ok', true, 'credited', true, 'chips', v_chips,
    'reward_chips', v_row.reward_chips);
exception when unique_violation then
  return jsonb_build_object('ok', false, 'error', 'transaction_reused');
end;
$$;

create or replace function public.finalize_play_purchase(
  p_user_id uuid,
  p_product_id text,
  p_purchase_token text,
  p_order_id text,
  p_package_name text,
  p_product_type text,
  p_raw_receipt jsonb,
  p_store_response jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_existing public.play_purchase_receipts%rowtype;
  v_diamonds integer := 0;
  v_months integer := 0;
  v_expiry timestamptz;
  v_chips bigint;
  v_wallet_diamonds integer;
  v_vip_until timestamptz;
begin
  if current_user not in ('service_role', 'postgres') then
    raise exception 'service_role_required' using errcode = '42501';
  end if;
  if p_package_name <> 'com.elli.bir' or coalesce(trim(p_purchase_token), '') = '' then
    return jsonb_build_object('ok', false, 'error', 'receipt_invalid');
  end if;

  select * into v_existing from public.play_purchase_receipts
   where purchase_token = p_purchase_token for update;
  if found then
    if v_existing.user_id <> p_user_id or v_existing.product_id <> p_product_id then
      return jsonb_build_object('ok', false, 'error', 'receipt_owned_by_another_account');
    end if;
    if v_existing.state = 'verified' then
      select chips, diamonds, vip_until into v_chips, v_wallet_diamonds, v_vip_until
        from public.profiles where id::text = p_user_id::text;
      return jsonb_build_object('ok', true, 'duplicate', true, 'chips', v_chips,
        'diamonds', v_wallet_diamonds, 'vip_until', v_vip_until);
    end if;
  else
    insert into public.play_purchase_receipts(
      user_id, product_id, purchase_token, order_id, package_name, product_type,
      raw_receipt, store_response
    ) values (
      p_user_id, p_product_id, p_purchase_token, p_order_id, p_package_name,
      p_product_type, coalesce(p_raw_receipt, '{}'::jsonb), coalesce(p_store_response, '{}'::jsonb)
    );
  end if;

  case p_product_id
    when 'onlinekahvem.diamond.10' then v_diamonds := 10;
    when 'onlinekahvem.diamond.50' then v_diamonds := 50;
    when 'onlinekahvem.diamond.150' then v_diamonds := 150;
    when 'onlinekahvem.vip.1month' then v_months := 1;
    when 'onlinekahvem.vip.6month' then v_months := 6;
    when 'onlinekahvem.vip.12month' then v_months := 12;
    else
      update public.play_purchase_receipts set state = 'rejected' where purchase_token = p_purchase_token;
      return jsonb_build_object('ok', false, 'error', 'product_invalid');
  end case;

  if v_diamonds > 0 then
    update public.profiles set diamonds = diamonds + v_diamonds
      where id::text = p_user_id::text;
  else
    begin
      v_expiry := nullif(p_store_response #>> '{lineItems,0,expiryTime}', '')::timestamptz;
    exception when others then v_expiry := null;
    end;
    update public.profiles
       set vip_until = greatest(coalesce(vip_until, now()), now())
                       + make_interval(months => v_months)
     where id::text = p_user_id::text;
    if v_expiry is not null then
      update public.profiles set vip_until = greatest(vip_until, v_expiry)
        where id::text = p_user_id::text;
    end if;
  end if;

  update public.play_purchase_receipts
     set state = 'verified', store_response = coalesce(p_store_response, '{}'::jsonb), verified_at = now()
   where purchase_token = p_purchase_token;
  select chips, diamonds, vip_until into v_chips, v_wallet_diamonds, v_vip_until
    from public.profiles where id::text = p_user_id::text;
  return jsonb_build_object('ok', true, 'chips', v_chips, 'diamonds', v_wallet_diamonds,
    'vip_until', v_vip_until, 'product_id', p_product_id);
exception when unique_violation then
  return jsonb_build_object('ok', false, 'error', 'receipt_reused');
end;
$$;

revoke all on function public.begin_rewarded_ad(text) from public, anon;
grant execute on function public.begin_rewarded_ad(text) to authenticated;
revoke all on function public.get_rewarded_ad_state(uuid) from public, anon;
grant execute on function public.get_rewarded_ad_state(uuid) to authenticated;
revoke all on function public.finalize_rewarded_ad(uuid, text, text, text, numeric) from public, anon, authenticated;
grant execute on function public.finalize_rewarded_ad(uuid, text, text, text, numeric) to service_role;
revoke all on function public.finalize_play_purchase(uuid, text, text, text, text, text, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.finalize_play_purchase(uuid, text, text, text, text, text, jsonb, jsonb) to service_role;
